apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aquarium
  region: us-west-2
  version: "1.17"

nodeGroups:
  - name: aquarium-ng
    desiredCapacity: 3
    minSize: 3
    maxSize: 5
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
    ssh: # An existing key pair for EC2 host test
      publicKeyName: kube
    volumeSize: 250
    kubeletExtraConfig:
        kubeReserved:
            cpu: "300m"
            memory: "300Mi"
            ephemeral-storage: "100Gi"
        kubeReservedCgroup: "/kube-reserved"
        systemReserved:
            cpu: "300m"
            memory: "300Mi"
            ephemeral-storage: "10Gi"
        evictionHard:
            memory.available:  "200Mi"
            nodefs.available: "10%"
        featureGates:
            DynamicKubeletConfig: true
            RotateKubeletServerCertificate: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]